version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - FLAG=uoftctf{IiIiIiI_am_a_pro_JSON_injector_IiIiIiI}
      - DB_HOST=db
      - MYSQL_USER=web
      - MYSQL_PASSWORD=J7zZR60PmM3TmaBk8sVW5fVz8za2svp1
      - MYSQL_DATABASE=ctf_challenge
  db:
    image: mysql:5.7
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: YNgBBTYdXcXKcQmYBzqYM7Xx9KoEDAy1
      MYSQL_DATABASE: ctf_challenge
      MYSQL_USER: web
      MYSQL_PASSWORD: J7zZR60PmM3TmaBk8sVW5fVz8za2svp1
    command: ["--sql-mode=NO_ENGINE_SUBSTITUTION,ERROR_FOR_DIVISION_BY_ZERO"]
    ports:
      - "3306:3306"
